config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root 'static_pages#home'

  get 'static_pages/help'

  get 'static_pages/about'

  get 'static_pages/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	validates :name,presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates(:email, presence: true, length: { maximum: 255 },format: { with: VALID_EMAIL_REGEX},
	                                         uniqueness: {case_sensitive: false})

	has_secure_password
	validates(:password, length: { minimum: 6})
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
    if @user.save 
      flash[:info]= "Welcome to this great App"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
  	params.require(:user).permit( :name,:email,:password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
Developed by Bony & Kevin 
<ul>

	<li><%= link_to "Home", root_path %></li>
	<li><%= link_to "About", static_pages_about_path %></li>
	<li><%= link_to "Help", static_pages_help_path %></li>
	<li><%= link_to "Contact", static_pages_contact_path %></li>
</ul>

app/views/layouts/_header.html.erb
<ul >
	<li><%= link_to "home", root_path %></li>
	<li><%= link_to "about", static_pages_about_url %></li>
	<li><%= link_to "help", static_pages_help_path %></li>
	<li><%= link_to "contact", static_pages_contact_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title)%> | Our App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>

    <%= yield %>
  <footer> <%= render 'layouts/footer' %></footer> 

  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>Its just Bony and Kevo working on this</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact Us</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<h1>Home Page</h1>
<p>A pair programming on our_app</p>

<%= link_to "Sign up now!", users_new_path %>

app/views/users/new.html.erb
<h1>Signup Form</h1>
<%= form_for(@user) do |f| %>

<%=  f.label :name %>
<%=  f.text_field :name %><br>
<%=  f.label :email %>
<%=  f.email_field :email %><br>
<%=  f.label :password %>
<%=  f.password_field :password %><br>
<%=  f.label :password_confirmation %>
<%=  f.password_field :password_confirmation %>
<%=  f.submit "signup" %> <br><br>

Already have an account? <%= link_to "Login", '#' %>
<% end %>

app/views/users/show.html.erb
<%provide(:title, @user.name)%>
<%= @user.name %>: <%= @user.email %>